version: '3.1'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bet
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
  betting:
    image: betting:latest
    container_name: betting
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres
      - POSTGRES_DB=bet
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
